
CREATE DATABASE "books";

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Author" text NOT NULL,
    "PublishYear" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);