version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
   
  books_api:
    container_name: books_api
    build:
      context: .
    restart: always
    environment:
      - ConnectionStrings__Postgres=User Id=postgres;Password=${POSTGRES_PASSWORD};Server=postgres;Port=5432;Database=books;
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: